[versions]
agp = "8.12.3"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"
androidx-activity = "1.12.2"
androidx-appcompat = "1.7.1"
androidx-core = "1.17.0"
androidx-espresso = "3.7.0"
androidx-lifecycle = "2.9.6"
androidx-testExt = "1.3.0"
composeHotReload = "1.0.0"
composeMultiplatform = "1.11.0-alpha01"
junit = "4.13.2"
settings = "1.3.0"
navigation-compose = "2.9.1"
materialIcons = "1.7.3"
material3 = "1.11.0-alpha01"
kotlinxSerializationCore = "1.9.0"
koinBom = "4.2.0-beta2"
filekit = "0.12.0"

kotlin = "2.2.20"
kotlinx-coroutines = "1.10.2"
ktor = "3.3.3"
logback = "1.5.23"
exposed = "1.0.0-rc-4"
postgresql = "42.7.8"
h2 = "2.4.240"
koin = "4.1.1"
khealth = "3.0.2"
hikari-cp = "7.0.2"
bcrypt = "0.4"
jakarta = "2.0.2"
mockk = "1.14.7"
junit-jupiter = "6.0.1"

[libraries]
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "composeMultiplatform" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "composeMultiplatform" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "composeMultiplatform" }
compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "composeMultiplatform" }
compose-components-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "composeMultiplatform" }
ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "composeMultiplatform" }
material-icons = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "materialIcons" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
material3-window-size = { module = "org.jetbrains.compose.material3:material3-window-size-class", version.ref = "material3" }

lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }

kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-testExt-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-testExt" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
kotlinx-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
multiplatform-settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "settings" }
multiplatform-settings-no-arg = { module = "com.russhwolf:multiplatform-settings-no-arg", version.ref = "settings" }
multiplatform-settings-serialization = { module = "com.russhwolf:multiplatform-settings-serialization", version.ref = "settings" }
navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationCore" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
koin-navigation3 = { module = "io.insert-koin:koin-compose-navigation3", version.ref = "koin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines"}

filekit-core = { module = "io.github.vinceglb:filekit-core", version.ref = "filekit" }
filekit-dialogs-compose = { module = "io.github.vinceglb:filekit-dialogs-compose", version.ref = "filekit" }
filekit-coil = { module = "io.github.vinceglb:filekit-coil", version.ref = "filekit" }

# Server
## Main
server-cors = { module = "io.ktor:ktor-server-cors", version.ref = "ktor" }
server-default-headers = { module = "io.ktor:ktor-server-default-headers", version.ref = "ktor" }
server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
server-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor" }
server-auth-jwt = { module = "io.ktor:ktor-server-auth-jwt", version.ref = "ktor" }
server-request-validation = { module = "io.ktor:ktor-server-request-validation", version.ref = "ktor" }
server-resources = { module = "io.ktor:ktor-server-resources", version.ref = "ktor" }
server-host-common = { module = "io.ktor:ktor-server-host-common", version.ref = "ktor" }
server-status-pages = { module = "io.ktor:ktor-server-status-pages", version.ref = "ktor" }
server-call-logging = { module = "io.ktor:ktor-server-call-logging", version.ref = "ktor" }
server-config-yaml = { module = "io.ktor:ktor-server-config-yaml", version.ref = "ktor" }
server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
server-openapi = { module = "io.ktor:ktor-server-openapi", version.ref = "ktor" }
server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
server-swagger = { module = "io.ktor:ktor-server-swagger", version.ref = "ktor" }
server-html-builder = { module = "io.ktor:ktor-server-html-builder", version.ref = "ktor" }
serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
khealth = { module = "dev.hayden:khealth", version.ref = "khealth" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
koin-ktor = { module = "io.insert-koin:koin-ktor", version.ref = "koin" }
koin-core-jvm = { module = "io.insert-koin:koin-core-jvm", version.ref = "koin" }
koin-slf4j = { module = "io.insert-koin:koin-logger-slf4j", version.ref = "koin" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
hikari-cp = { module = "com.zaxxer:HikariCP", version.ref = "hikari-cp" }
bcrypt = { module = "org.mindrot:jbcrypt", version.ref = "bcrypt" }
jakarta-mail = { module = "com.sun.mail:jakarta.mail", version.ref = "jakarta" }
client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }

server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }