name: Deploy to VPS

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - composeApp/**
      - docs/**
      - "**/*.example"
      - "**/*.yml"
      - "**/*.yaml"
      - "**/*.json"
      - "**/*.lock"
      - "**/**.run.xml"
      - ".gitignore"
      - src/test/**
    workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to VPS and Deploy
        uses: appleboy/ssh-action@v1.2.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            /root/deploy_lilac_kas.sh